"""Tests for generated third-party notices."""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import TYPE_CHECKING, Any

from scripts import generate_third_party_notices
from tests.helpers.automation import RunRecorder, fake_which

if TYPE_CHECKING:
    import pytest


def _package(
    name: str,
    version: str,
    license_text: str,
    *,
    package_id: str | None = None,
    repository: str | None = None,
) -> dict[str, Any]:
    return {
        "name": name,
        "version": version,
        "id": package_id
        or f"registry+https://github.com/rust-lang/crates.io-index#{name}@{version}",
        "license": license_text,
        "license_file": None,
        "repository": repository,
        "source": "registry+https://github.com/rust-lang/crates.io-index",
    }


def test_runtime_notice_entries_follow_normal_dependency_edges_only() -> None:
    root_id = "path+file:///repo#1.0.0"
    runtime_id = "registry+https://github.com/rust-lang/crates.io-index#runtime@1.0.0"
    transitive_id = "registry+https://github.com/rust-lang/crates.io-index#transitive@2.0.0"
    build_only_id = "registry+https://github.com/rust-lang/crates.io-index#build-only@3.0.0"
    metadata: dict[str, Any] = {
        "packages": [
            {
                "name": "oxipng-pybind",
                "version": "1.0.0",
                "id": root_id,
                "license": "Unlicense",
                "source": None,
                "repository": "https://github.com/pdomain/oxipng-pybind",
            },
            _package(
                "runtime",
                "1.0.0",
                "MIT",
                package_id=runtime_id,
                repository="https://example.invalid/runtime",
            ),
            _package("transitive", "2.0.0", "Apache-2.0", package_id=transitive_id),
            _package("build-only", "3.0.0", "MIT", package_id=build_only_id),
        ],
        "resolve": {
            "root": root_id,
            "nodes": [
                {
                    "id": root_id,
                    "deps": [
                        {
                            "name": "runtime",
                            "pkg": runtime_id,
                            "dep_kinds": [{"kind": None, "target": None}],
                        },
                        {
                            "name": "build_only",
                            "pkg": build_only_id,
                            "dep_kinds": [{"kind": "build", "target": None}],
                        },
                    ],
                },
                {
                    "id": runtime_id,
                    "deps": [
                        {
                            "name": "transitive",
                            "pkg": transitive_id,
                            "dep_kinds": [{"kind": None, "target": None}],
                        }
                    ],
                },
                {"id": transitive_id, "deps": []},
                {"id": build_only_id, "deps": []},
            ],
        },
    }

    entries = generate_third_party_notices.runtime_rust_entries(metadata)

    assert [entry.name for entry in entries] == ["runtime", "transitive"]
    assert entries[0].repository == "https://example.invalid/runtime"


def test_rendered_notices_include_generated_marker_and_python_runtime_status() -> None:
    rendered = generate_third_party_notices.render_notices(
        [
            generate_third_party_notices.NoticeEntry(
                name="runtime",
                version="1.0.0",
                license="MIT",
                repository="https://example.invalid/runtime",
            )
        ],
        python_runtime_dependencies=[],
    )

    assert "<!-- generated by scripts/generate_third_party_notices.py -->" in rendered
    assert "## Runtime Rust Dependencies" in rendered
    assert "- Project: [runtime](https://example.invalid/runtime)" in rendered
    assert "- Version: 1.0.0" in rendered
    assert "- License: MIT" in rendered
    assert "## Runtime Python Dependencies" in rendered
    assert "No Python runtime dependencies are currently distributed." in rendered


def test_third_party_notices_match_generator_output() -> None:
    generated = generate_third_party_notices.generate()
    notices = Path("THIRD_PARTY_NOTICES.md").read_text(encoding="utf-8")

    assert notices == generated


def test_notice_generator_cli_check_reports_drift(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    notice_path = tmp_path / "THIRD_PARTY_NOTICES.md"
    notice_path.write_text("stale\n", encoding="utf-8")
    monkeypatch.setattr(generate_third_party_notices, "NOTICE_PATH", notice_path)
    monkeypatch.setattr(generate_third_party_notices, "generate", lambda: "fresh\n")

    assert generate_third_party_notices.main(["--check"]) == 1


def test_notice_generator_cli_write_updates_file(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    notice_path = tmp_path / "THIRD_PARTY_NOTICES.md"
    monkeypatch.setattr(generate_third_party_notices, "NOTICE_PATH", notice_path)
    monkeypatch.setattr(generate_third_party_notices, "generate", lambda: "fresh\n")

    assert generate_third_party_notices.main(["--write"]) == 0
    assert notice_path.read_text(encoding="utf-8") == "fresh\n"


def test_notice_generator_runs_cargo_metadata_with_locked_flag(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    recorder = RunRecorder(stdout='{"ok": true}')

    monkeypatch.setattr(generate_third_party_notices, "resolve_executable", fake_which())
    monkeypatch.setattr(subprocess, "run", recorder)

    assert generate_third_party_notices.load_cargo_metadata() == {"ok": True}
    assert len(recorder.calls) == 1
    call = recorder.calls[0]
    assert call.command == ["/fake/bin/cargo", "metadata", "--locked", "--format-version", "1"]
    assert call.cwd == generate_third_party_notices.ROOT
    assert call.check is True
    assert call.capture_output is True
    assert call.text is True
