"""Tests for packaging metadata policy."""

from __future__ import annotations

from pathlib import Path

from packaging.requirements import Requirement

from scripts._toml_compat import load_file


def test_script_security_ignores_are_line_scoped() -> None:
    pyproject = load_file("pyproject.toml")
    bump_script = Path("scripts/bump_upstream.py").read_text(encoding="utf-8")

    script_ignores = pyproject["tool"]["ruff"]["lint"]["per-file-ignores"]["scripts/*.py"]
    assert "S310" not in script_ignores
    assert "S603" not in script_ignores
    assert "# noqa: S310" in bump_script
    assert "# noqa: S603" in bump_script


def test_third_party_notices_are_packaged() -> None:
    pyproject = load_file("pyproject.toml")
    notices = Path("THIRD_PARTY_NOTICES.md").read_text(encoding="utf-8")

    assert pyproject["project"]["license-files"] == ["LICENSE", "THIRD_PARTY_NOTICES.md"]
    assert "<!-- generated by scripts/generate_third_party_notices.py -->" in notices
    for dependency in ("pyo3", "indexmap", "libdeflater", "zopfli", "rayon"):
        assert dependency in notices


def test_pillow_dependency_keeps_python_310_wheel_compatibility() -> None:
    pyproject = load_file("pyproject.toml")

    test_dependencies = pyproject["dependency-groups"]["test"]
    pillow_requirements = [
        Requirement(dependency)
        for dependency in test_dependencies
        if Requirement(dependency).name == "pillow"
    ]
    assert len(pillow_requirements) == 1
    pillow = pillow_requirements[0]
    assert str(pillow.specifier) == ">=12.2"
    assert pillow.marker is not None
    assert not pillow.marker.evaluate({"python_version": "3.10"})
    assert pillow.marker.evaluate({"python_version": "3.11"})


def test_python_314_classifier_matches_api_matrix() -> None:
    matrix = Path(".github/workflows/api-matrix.yml").read_text(encoding="utf-8")
    pyproject = load_file("pyproject.toml")

    if '"3.14"' in matrix:
        assert "Programming Language :: Python :: 3.14" in pyproject["project"]["classifiers"]


def test_api_surface_records_python_rowfilter_compatibility() -> None:
    manifest = load_file("docs/api-surface/oxipng-10.1.1.toml")

    assert manifest["python_compat"]["RowFilter"]["aliases"]["brute"] == (
        "Python facade compatibility alias; maps through FilterStrategy, not upstream RowFilter"
    )
