"""Tests for packaging metadata policy."""

from __future__ import annotations

from pathlib import Path


def test_script_security_ignores_are_line_scoped() -> None:
    pyproject = Path("pyproject.toml").read_text(encoding="utf-8")
    bump_script = Path("scripts/bump_upstream.py").read_text(encoding="utf-8")

    assert '"scripts/*.py" = ["S310", "S603", "T201"]' not in pyproject
    assert "# noqa: S310" in bump_script
    assert "# noqa: S603" in bump_script


def test_third_party_notices_are_packaged() -> None:
    pyproject = Path("pyproject.toml").read_text(encoding="utf-8")
    notices = Path("THIRD_PARTY_NOTICES.md").read_text(encoding="utf-8")

    assert 'license-files = ["LICENSE", "THIRD_PARTY_NOTICES.md"]' in pyproject
    assert "<!-- generated by scripts/generate_third_party_notices.py -->" in notices
    for dependency in ("pyo3", "indexmap", "libdeflater", "zopfli", "rayon"):
        assert dependency in notices


def test_pillow_dependency_keeps_python_310_wheel_compatibility() -> None:
    pyproject = Path("pyproject.toml").read_text(encoding="utf-8")

    assert "\"pillow>=12.2; python_version >= '3.11'\"" in pyproject
    assert "python_version < '3.11'" not in pyproject


def test_python_314_classifier_matches_api_matrix() -> None:
    matrix = Path(".github/workflows/api-matrix.yml").read_text(encoding="utf-8")
    pyproject = Path("pyproject.toml").read_text(encoding="utf-8")

    if '"3.14"' in matrix:
        assert '"Programming Language :: Python :: 3.14"' in pyproject


def test_api_surface_records_python_rowfilter_compatibility() -> None:
    manifest = Path("docs/api-surface/oxipng-10.1.1.toml").read_text(encoding="utf-8")

    assert "[python_compat.RowFilter.aliases]" in manifest
    assert (
        'brute = "Python facade compatibility alias; maps through FilterStrategy, not upstream RowFilter"'
        in manifest
    )
