"""Generate third-party notices from locked dependency metadata."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parents[1]
NOTICE_PATH = ROOT / "THIRD_PARTY_NOTICES.md"


@dataclass(frozen=True, order=True)
class NoticeEntry:
    """One dependency notice entry."""

    name: str
    version: str
    license: str
    repository: str | None


def resolve_executable(name: str) -> str:
    """Resolve an executable path for subprocess calls."""
    executable = shutil.which(name)
    if executable is None:
        raise RuntimeError(f"{name} executable not found on PATH")
    return executable


def load_cargo_metadata() -> dict[str, Any]:
    """Return locked Cargo metadata."""
    result = subprocess.run(  # noqa: S603  # fixed cargo command, executable resolved first
        [resolve_executable("cargo"), "metadata", "--locked", "--format-version", "1"],
        check=True,
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    return cast("dict[str, Any]", json.loads(result.stdout))


def _normal_dependency_ids(metadata: dict[str, Any]) -> set[str]:
    resolve = cast("dict[str, Any]", metadata["resolve"])
    root_id = cast("str", resolve["root"])
    nodes = {
        cast("str", node["id"]): node for node in cast("list[dict[str, Any]]", resolve["nodes"])
    }
    seen: set[str] = set()
    pending = [root_id]

    while pending:
        current = pending.pop()
        node = nodes[current]
        for dep in cast("list[dict[str, Any]]", node.get("deps", [])):
            dep_kinds = cast("list[dict[str, Any]]", dep.get("dep_kinds", []))
            if not any(kind.get("kind") is None for kind in dep_kinds):
                continue
            package_id = cast("str", dep["pkg"])
            if package_id not in seen:
                seen.add(package_id)
                pending.append(package_id)

    return seen


def runtime_rust_entries(metadata: dict[str, Any]) -> list[NoticeEntry]:
    """Return notices for normal Rust dependencies reachable from this package."""
    dependency_ids = _normal_dependency_ids(metadata)
    packages = {
        cast("str", package["id"]): package
        for package in cast("list[dict[str, Any]]", metadata["packages"])
    }
    entries = [
        NoticeEntry(
            name=cast("str", package["name"]),
            version=cast("str", package["version"]),
            license=cast("str | None", package.get("license"))
            or cast("str | None", package.get("license_file"))
            or "UNKNOWN",
            repository=cast("str | None", package.get("repository")),
        )
        for package_id, package in packages.items()
        if package_id in dependency_ids and package.get("source") is not None
    ]
    return sorted(entries, key=lambda entry: (entry.name.lower(), entry.version))


def python_runtime_dependencies() -> list[str]:
    """Return declared Python runtime dependency strings."""
    pyproject = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    project = cast("dict[str, Any]", pyproject.get("project", {}))
    return sorted(cast("list[str]", project.get("dependencies", [])))


def _render_project_line(entry: NoticeEntry) -> str:
    if entry.repository:
        return f"- Project: [{entry.name}]({entry.repository})"
    return f"- Project: {entry.name}"


def render_notices(
    rust_entries: list[NoticeEntry], *, python_runtime_dependencies: list[str]
) -> str:
    """Render the notice document."""
    lines = [
        "# Third-Party Notices",
        "",
        "<!-- generated by scripts/generate_third_party_notices.py -->",
        "",
        "`oxipng-pybind` wraps upstream `oxipng`.",
        "",
        "The Python wheel includes a native Rust extension. Runtime Rust",
        "dependencies retain their upstream licenses and notices.",
        "",
        "## Runtime Rust Dependencies",
        "",
    ]
    for entry in rust_entries:
        lines.extend(
            [
                _render_project_line(entry),
                f"- Version: {entry.version}",
                f"- License: {entry.license}",
                "",
            ]
        )

    lines.extend(["## Runtime Python Dependencies", ""])
    if python_runtime_dependencies:
        lines.extend(f"- {dependency}" for dependency in python_runtime_dependencies)
    else:
        lines.append("No Python runtime dependencies are currently distributed.")

    lines.extend(["", "Run `make rust-deny` to verify Rust dependency license policy.", ""])
    return "\n".join(lines)


def generate() -> str:
    """Generate notices from current locked dependencies."""
    return render_notices(
        runtime_rust_entries(load_cargo_metadata()),
        python_runtime_dependencies=python_runtime_dependencies(),
    )


def main(argv: list[str] | None = None) -> int:
    """Run the notice generator."""
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail if notices drift")
    mode.add_argument("--write", action="store_true", help="write notices")
    args = parser.parse_args(argv)

    generated = generate()
    if args.write:
        NOTICE_PATH.write_text(generated, encoding="utf-8")
        return 0

    current = NOTICE_PATH.read_text(encoding="utf-8")
    if current != generated:
        print("THIRD_PARTY_NOTICES.md is out of date", file=sys.stderr)
        print("Run: uv run --group dev scripts/generate_third_party_notices.py --write")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
