name: ci

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    name: source ci
    runs-on: ubuntu-latest
    env:
      UV_PYTHON: "3.13"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          version: 0.11.12
      - uses: dtolnay/rust-toolchain@1.95.0
        with:
          components: clippy
      - name: Install cargo-deny
        uses: taiki-e/install-action@60ae4ce63c7aeb6e96d7f572c1ec7fafbb17ca80
        with:
          tool: cargo-deny@0.19.7
      - run: make ci
