name: ci

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    name: source ci
    runs-on: ubuntu-latest
    env:
      UV_PYTHON: "3.13"
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version: 0.11.12
      - uses: dtolnay/rust-toolchain@1.95.0
        with:
          components: clippy
      - name: Install cargo-deny
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny@0.19.7
      - run: make ci
